### ISSUE TITLE
关于 generate_dataset

### ISSUE THREAD

**Issue by tikboaHIT** [SHERLOCKLS/datafountain_siweituxin_autodriver_seg#1]
你好，在你的代码中，我发现你自定义了一个auto的dataset类，但是仓库中并没有这个，你能上传这个dataset类吗？config中auto如下

class Configuration():
	def __init__(self):
		self.ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname("__file__"),'..','..'))
		self.EXP_NAME = 'deeplabv3+'

		self.DATA_NAME = 'auto'
		self.DATA_AUG = True
		self.DATA_WORKERS = 8
		self.DATA_RESCALE = 512
		self.DATA_RANDOMCROP = 512
		self.DATA_RANDOMROTATION = 0
		self.DATA_RANDOMSCALE = 3

**Comment by SHERLOCKLS** [comment]
Files have been uploaded, thanks for your remind.
